# Shujaa Studio Configuration
# Production-ready settings for local deployment

# Core paths
work_base: ./outputs
bark_cli: ./voice_engine.py
sdxl_path: ./models/sdxl
musicgen_script: ./music_engine.py
whisper_cmd: whisper
ffmpeg: ffmpeg

# Performance settings - Enhanced with GPU Fallback
use_cuda: true  # Now intelligently managed by hybrid GPU system
enable_gpu_fallback: true  # Enable cloud GPU fallbacks
enable_news_mode: true  # Enable news-to-video functionality
default_scenes: 3
vertical: true

# GPU Fallback Configuration
gpu_fallback:
  enable_cloud: false  # Set to true when cloud providers configured
  local_priority: true  # Prefer local GPU when available
  cost_limit_per_hour: 5.0  # Max hourly spend on cloud GPU
  fallback_timeout: 30  # Seconds before falling back to CPU

# News Video Configuration  
news_video:
  default_duration: 30  # Default video length in seconds
  african_context: true  # Enhance with African cultural context
  supported_styles: ["breaking", "feature", "analysis", "sports", "business"]
  auto_categorize: true  # Automatically detect news categories

# Video settings
video_fps: 24
video_width: 1080
video_height: 1920

# API settings
api_host: 0.0.0.0
api_port: 8000
ui_port: 7860

# Model paths (update these to your actual paths)
models:
  sdxl: ./models/sdxl
  bark: ./bark
  whisper: ./models/whisper

# Output settings
output:
  format: mp4
  quality: high
  enable_subtitles: true
  enable_music: true

# Platform export settings
export:
  tiktok:
    resolution: [1080, 1920]
    max_size_mb: 287
  whatsapp:
    resolution: [720, 1280]
    max_size_mb: 16
  instagram:
    resolution: [1080, 1920]
    max_size_mb: 100
