# Core Configuration for Shujaa Studio
app:
  name: "Shujaa Studio"
  version: "0.1.0"
  environment: "development" # development, staging, production
  database_name: "shujaa_db" # Name of the SQLite database file

# API Keys and Credentials (sensitive, loaded from .env or secrets management)
api_keys:
  huggingface: "${HF_API_KEY}" # Loaded from environment variable
  google_news: "" # Optional: NewsAPI.org key
  youtube_client_secret_file: "client_secret.json" # Path to Google client secret JSON

# Model Configuration
models:
  text_generation:
    hf_api_id: "mistralai/Mistral-7B-Instruct-v0.2" # Default for scene generation
    local_fallback_path: "" # Path to local LLM model (e.g., LLaMA.cpp compatible)
  image_generation:
    hf_api_id: "stabilityai/stable-diffusion-xl-base-1.0" # Example HF model
    local_fallback_path: "" # Path to local Stable Diffusion model
  voice_synthesis:
    hf_api_id: "suno/bark"
    local_fallback_path: "" # Path to local Bark/CoquiTTS model
  speech_to_text:
    hf_api_id: "openai/whisper-large-v2"
    local_fallback_path: "" # Path to local Whisper model

# GPU Management (HybridGPUManager settings)
gpu_manager:
  enable_cloud_gpu: false # Set to true to enable RunPod/Vast.ai integration
  cloud_providers_config: "gpu_cloud_config.json" # Configuration for cloud GPU providers

# Video Generation Settings
video:
  default_fps: 24
  default_image_duration: 3 # seconds per image
  output_resolution: [1920, 1080] # [width, height]
  temp_dir: "temp"
  output_dir: "output"
  music_dir: "music"

# Logging Configuration
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "logs/shujaa.log"
  max_bytes: 10485760 # 10 MB
  backup_count: 5
  enable_audit_log: true
  audit_log_level: "INFO"
  audit_log_file: "logs/shujaa_audit.log"

auth:
  access_token_expire_minutes: 30 # JWT token expiry time in minutes

security:
  encryption_password: "your_super_secret_encryption_password" # CHANGE THIS IN PRODUCTION
  encryption_salt: "a_random_salt_string_for_encryption" # CHANGE THIS IN PRODUCTION