# // [TASK]: Create Kubernetes HorizontalPodAutoscaler manifest
# // [GOAL]: Automatically scale the application based on CPU utilization
# // [ELITE_CURSOR_SNIPPET]: aihandle

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shujaa-studio-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shujaa-studio-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80