# // [TASK]: Create Helm values.yaml
# // [GOAL]: Define the default values for the Helm chart
# // [ELITE_CURSOR_SNIPPET]: aihandle

replicaCount: 2

image:
  repository: shujaa-studio-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: shujaa-studio.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}