# // [TASK]: Create GitHub Actions CI workflow
# // [GOAL]: Automate testing, linting, and building of the application
# // [ELITE_CURSOR_SNIPPET]: aihandle

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pip-audit
      run: pip install pip-audit

    - name: Run dependency vulnerability scan
      run: pip-audit --strict

    - name: Lint with ruff
      run: |
        pip install ruff
        ruff check .

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag shujaa-studio-api:latest