name: Shujaa Studio CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest fastapi uvicorn[standard] starlette-prometheus locust

    - name: Lint with ruff (placeholder)
      run: |
        pip install ruff
        # In a real CI, you would have a ruff.toml configuration
        ruff check .

    - name: Run tests with pytest
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build . -t shujaa-studio:latest

    - name: Run Snyk SCA
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test

    - name: Run Trivy vulnerability scan (filesystem)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'HIGH,CRITICAL'
        format: 'table'
        output: 'trivy-results.txt'

    - name: Run Trivy vulnerability scan (image)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'shujaa-studio:latest'
        format: 'table'
        output: 'trivy-image-results.txt'
        severity: 'HIGH,CRITICAL'

    - name: Install Cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v2.0.0' # Use a specific version

    - name: Sign and Push Image
      env:
        COSIGN_EXPERIMENTAL: "true"
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }} # Use a strong, dedicated password
      run: |
        cosign sign --yes shujaa-studio:latest

    - name: Generate and Push SBOM
      env:
        COSIGN_EXPERIMENTAL: "true"
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: |
        cosign generate-sbom shujaa-studio:latest > sbom.spdx.json
        # You might push this to a registry or store it as an artifact
        # cosign attach sbom --sbom sbom.spdx.json shujaa-studio:latest
