name: Shujaa Studio CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest fastapi uvicorn[standard] starlette-prometheus locust

    - name: Lint with ruff (placeholder)
      run: |
        pip install ruff
        # In a real CI, you would have a ruff.toml configuration
        ruff check .

    - name: Run tests with pytest
      run: |
        pytest

    - name: Build Docker image (placeholder)
      run: |
        echo "TODO: Add Dockerfile and docker build command"
        # docker build . -t shujaa-studio:latest
