# // [TASK]: Create GitHub Actions CI workflow
# // [GOAL]: Automate testing, linting, and building of the application
# // [ELITE_CURSOR_SNIPPET]: aihandle

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pip-audit
      run: pip install pip-audit

    - name: Run dependency vulnerability scan
      run: pip-audit --strict

    - name: Lint with ruff
      run: |
        pip install ruff
        ruff check .

    - name: Test with pytest
      run: |
        pip install pytest
        pytest --cov=. --cov-report=xml # ADD --cov for coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3 # ADD THIS STEP
      with:
        file: ./coverage.xml # Path to coverage report generated by pytest --cov-report=xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Run Static Application Security Testing (SAST) # ADD THIS STEP
      run: |
        echo "Conceptual SAST scan using a tool like Bandit or Semgrep"
        # pip install bandit
        # bandit -r . -ll -f json -o bandit-report.json
        # semgrep --config "p/python" --json -o semgrep-report.json .
        echo "SAST scan completed. Review bandit-report.json and semgrep-report.json"

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag shujaa-studio-api:latest