dependencies:
  - name: "torch"
    min_version: "2.0.0"
    max_version: "2.3.0"
  - name: "transformers"
    min_version: "4.40.0"
    max_version: "4.50.0"
  - name: "Babel"
    min_version: "2.12.1"
  - name: "starlette-prometheus"
    min_version: "0.14.0"
  - name: "lama-cleaner"
    min_version: "0.14.0"
    venv: "venv312-lama"
  - name: "sdxl-turbo"
    path: "models/sdxl-turbo"
    min_version: "0.9.4"
