dependencies:
  - name: "torch"
    min_version: "2.0.0"
    kind: pip
  - name: "transformers"
    min_version: "4.40.0"
    kind: pip
  - name: "Babel"
    min_version: "2.12.1"
    kind: pip
  - name: "starlette-prometheus"
    min_version: "0.10.0"
    kind: pip
  - name: "opentelemetry-instrumentation-fastapi"
    min_version: "0.43b0"
    kind: pip
  - name: "opentelemetry-sdk"
    min_version: "1.25.0"
    kind: pip
  - name: "opentelemetry-api"
    min_version: "1.25.0"
    kind: pip
  - name: "redis"
    min_version: "5.0.0"
    kind: pip
  - name: "python-multipart"
    min_version: "0.0.6"
    kind: pip
  - name: "lama-cleaner"
    min_version: "0.14.0"
    venv: "venv312-lama"
    kind: pip
  - name: "sdxl-turbo"
    path: "models/sdxl-turbo"
    kind: model
  - kind: pip
    name: torchvision
  - kind: pip
    name: torchaudio
  - kind: pip
    name: diffusers
  - kind: pip
    name: moviepy
  - kind: pip
    name: ffmpeg-python
  - kind: pip
    name: gradio
  - kind: pip
    name: av
  - kind: pip
    name: faster-whisper
  - kind: pip
    name: git+https://github.com/openai/whisper.git@v20231117
  - kind: pip
    name: git+https://github.com/suno-ai/bark.git
  - kind: pip
    name: pyttsx3
  - kind: pip
    name: soundfile
  - kind: pip
    name: Pillow
  - kind: pip
    name: numpy
  - kind: pip
    name: scipy
  - kind: pip
    name: accelerate
  - kind: pip
    name: safetensors
  - kind: pip
    name: huggingface-hub
  - kind: pip
    name: tokenizers
  - kind: pip
    name: xformers
  - kind: pip
    name: einops
  - kind: pip
    name: funcy
  - kind: pip
    name: encodec
  - kind: pip
    name: edge-tts
  - kind: pip
    name: librosa
  - kind: pip
    name: opencv-python
  - kind: pip
    name: opencv-contrib-python
  - kind: pip
    name: requests
  - kind: pip
    name: beautifulsoup4
  - kind: pip
    name: gtts
  - kind: pip
    name: feedparser
  - kind: pip
    name: huggingface_hub
  - kind: pip
    name: google-api-python-client
  - kind: pip
    name: google-auth-oauthlib
  - kind: pip
    name: google-auth-httplib2
  - kind: pip
    name: pyyaml
  - kind: pip
    name: dotmap
  - kind: pip
    name: boto3
  - kind: pip
    name: celery
  - kind: pip
    name: aiohttp
  - kind: pip
    name: fastapi
  - kind: pip
    name: uvicorn[standard]
  - kind: pip
    name: pyjwt
  - kind: pip
    name: cryptography
  - kind: pip
    name: SQLAlchemy
  - kind: pip
    name: passlib[bcrypt]
  - kind: pip
    name: fastapi-limiter
  - kind: pip
    name: python-dotenv
  - kind: pip
    name: psutil
  - kind: pip
    name: tqdm
  - kind: pip
    name: colorama
  - kind: pip
    name: click
  - kind: pip
    name: py-spy
  - kind: node
    name: autoprefixer
    workdir: frontend
  - kind: node
    name: axios
    workdir: frontend
  - kind: node
    name: clsx
    workdir: frontend
  - kind: node
    name: critters
    workdir: frontend
  - kind: node
    name: next
    workdir: frontend
  - kind: node
    name: postcss
    workdir: frontend
  - kind: node
    name: react
    workdir: frontend
  - kind: node
    name: react-dom
    workdir: frontend
  - kind: node
    name: react-icons
    workdir: frontend
  - kind: node
    name: recharts
    workdir: frontend
  - kind: node
    name: tailwind-merge
    workdir: frontend
  - kind: node
    name: use-debounce
    workdir: frontend
  - kind: node
    name: '@eslint/eslintrc'
    workdir: frontend
  - kind: node
    name: '@tailwindcss/postcss'
    workdir: frontend
  - kind: node
    name: '@testing-library/jest-dom'
    workdir: frontend
  - kind: node
    name: '@testing-library/react'
    workdir: frontend
  - kind: node
    name: '@types/jest'
    workdir: frontend
  - kind: node
    name: '@types/node'
    workdir: frontend
  - kind: node
    name: '@types/react'
    workdir: frontend
  - kind: node
    name: '@types/react-dom'
    workdir: frontend
  - kind: node
    name: babel-jest
    workdir: frontend
  - kind: node
    name: eslint
    workdir: frontend
  - kind: node
    name: eslint-config-next
    workdir: frontend
  - kind: node
    name: jest
    workdir: frontend
  - kind: node
    name: jest-environment-jsdom
    workdir: frontend
  - kind: node
    name: tailwindcss
    workdir: frontend
  - kind: node
    name: ts-jest
    workdir: frontend
  - kind: node
    name: typescript
    workdir: frontend